# GET http://127.0.0.1/blog/wp-json/wp/v2/get-post-by-id/335
#######

# GET http://127.0.0.1/blog/wp-json/wp/v2/get-all-posts/?year=2021

#######
# GET http://127.0.0.1/blog/wp-json/wp/v2/pages?slug="home"
# GET http://127.0.0.1/blog/wp-json/wp/v2/get-global-styles


#######
# GET http://127.0.0.1/blog/wp-json/wp/v2/get-nav-links

#######
# GET http://127.0.0.1/blog/wp-json/wp/v2/get-page-resources/home


#######
GET http://127.0.0.1/blog/wp-json/wp/v2/get-page-body/home
